import type {
  ActionAgreement,
  ActivityItem,
  OperatingReview,
  Program,
  RelationshipStat,
  ResourceItem,
  ReviewAgendaItem,
  ReviewParticipant,
  WorkItem,
} from "@/lib/types/portal";

export const relationshipStats: RelationshipStat[] = [
  { label: "Active Programs", value: "3", subtext: "Across your SageSure relationship" },
  { label: "Needs Attention", value: "6", subtext: "Items awaiting carrier input" },
  { label: "In Motion", value: "11", subtext: "Requests and actions progressing" },
  { label: "Delivered This Month", value: "24", subtext: "Reports, updates, and resources posted" },
];

export const programs: Program[] = [
  {
    id: "interboro-preferred",
    carrierGroup: "Valence Insurance Holdings",
    carrier: "Interboro",
    name: "Interboro Preferred",
    status: "Active",
    openWorkCount: 4,
    nextReviewDate: "Mar 29, 2026",
    latestUpdate: "January loss ratio package posted",
    metrics: { production: "↑ 4.2%", retention: "→ 88.1%", lossRatio: "↓ 2.1 pts" },
  },
  {
    id: "safechoice-program",
    carrierGroup: "SafeChoice Group",
    carrier: "SafeChoice",
    name: "SafeChoice Program",
    status: "Active",
    openWorkCount: 3,
    nextReviewDate: "Apr 03, 2026",
    latestUpdate: "New underwriting guideline update",
    metrics: { production: "→ 0.8%", retention: "↑ 1.4 pts", lossRatio: "→ 61.3%" },
  },
  {
    id: "interboro-specialty",
    carrierGroup: "Valence Insurance Holdings",
    carrier: "Interboro",
    name: "Interboro Specialty",
    status: "Watch",
    openWorkCount: 7,
    nextReviewDate: "Apr 07, 2026",
    latestUpdate: "Modeling request currently in progress",
    metrics: { production: "↓ 1.3%", retention: "→ 84.7%", lossRatio: "↑ 3.8 pts" },
  },
];

export const activityItems: ActivityItem[] = [
  {
    id: "a1",
    programId: "interboro-preferred",
    type: "scheduled_report_available",
    title: "Monthly financial report available",
    detail: "Interboro Preferred March report was posted to the Resource Library.",
    timestamp: "Today • 9:12 AM",
    timeBucket: "Today",
    priority: "High",
    relatedEntityType: "resource",
    relatedEntityId: "r1",
  },
  {
    id: "a2",
    programId: "safechoice-program",
    type: "request_stage_changed",
    title: "Request moved to Complete - Pending Review",
    detail: "Underwriting guideline clarification is ready for review.",
    timestamp: "Today • 8:40 AM",
    timeBucket: "Today",
    priority: "Normal",
    relatedEntityType: "work",
    relatedEntityId: "w2",
  },
  {
    id: "a3",
    programId: "interboro-specialty",
    type: "review_scheduled",
    title: "Operating Review scheduled",
    detail: "Review scheduled for Apr 07, 2026 with pre-read materials attached.",
    timestamp: "Yesterday • 4:20 PM",
    timeBucket: "This Week",
    priority: "Normal",
    relatedEntityType: "review",
    relatedEntityId: "or-6",
  },
  {
    id: "a4",
    programId: "interboro-specialty",
    type: "resource_published",
    title: "Cat response bulletin posted",
    detail: "New catastrophe prep resource is now visible to program users.",
    timestamp: "Yesterday • 2:05 PM",
    timeBucket: "This Week",
    priority: "Normal",
    relatedEntityType: "resource",
    relatedEntityId: "r5",
  },
];

export const resources: ResourceItem[] = [
  {
    id: "r1",
    title: "March Financial Report",
    programId: "interboro-preferred",
    topic: "Financial Reporting",
    resourceType: "Report",
    dateLabel: "Mar 18, 2026",
    audience: "Leadership / Finance",
    description: "Monthly performance package with production, retention, and loss ratio views.",
  },
  {
    id: "r2",
    title: "February Operating Review Deck",
    programId: "interboro-preferred",
    topic: "Operating Reviews",
    resourceType: "Review Deck",
    dateLabel: "Mar 3, 2026",
    audience: "Leadership / Operations",
    description: "Plan vs Actual review, portfolio movement, and action items.",
  },
  {
    id: "r3",
    title: "Underwriting Guideline Update",
    programId: "safechoice-program",
    topic: "Product & Underwriting",
    resourceType: "Product Update",
    dateLabel: "Feb 18, 2026",
    audience: "Operations / Underwriting",
    description: "Latest underwriting changes affecting new business flow.",
  },
  {
    id: "r4",
    title: "Claims Services Addendum",
    programId: "interboro-specialty",
    topic: "Agreements",
    resourceType: "Governing Doc",
    dateLabel: "Feb 11, 2026",
    audience: "Legal / Leadership",
    description: "Updated agreement language related to program servicing responsibilities.",
  },
  {
    id: "r5",
    title: "Catastrophe Readiness Bulletin",
    programId: "interboro-specialty",
    topic: "Cat Response",
    resourceType: "Guide",
    dateLabel: "Yesterday",
    audience: "Operations",
    description: "Current operating guidance for catastrophe season readiness.",
  },
  {
    id: "r6",
    title: "Program Administrator Agreement Restatement",
    programId: "interboro-preferred",
    topic: "Agreements",
    resourceType: "Governing Doc",
    dateLabel: "Today",
    audience: "Leadership / Legal",
    description: "Restated administrator agreement consolidating prior amendments.",
  },
  {
    id: "r7",
    title: "Commission Settlement Template",
    programId: "interboro-preferred",
    topic: "Contracting",
    resourceType: "Guide",
    dateLabel: "Mar 12, 2026",
    audience: "Finance / Leadership",
    description: "Template and guidance for commission settlement reconciliation.",
  },
  {
    id: "r8",
    title: "Retention Monitoring Package",
    programId: "safechoice-program",
    topic: "Reporting & Analysis",
    resourceType: "Report",
    dateLabel: "Mar 19, 2026",
    audience: "Leadership / Operations",
    description: "A new package focused on retention trends, segments, and watch-outs.",
  },
  {
    id: "r9",
    title: "Claims Readiness Summary",
    programId: "interboro-specialty",
    topic: "Claims",
    resourceType: "Meeting Summary",
    dateLabel: "Mar 15, 2026",
    audience: "Operations / Claims",
    description: "Post-review summary outlining claims readiness, bottlenecks, and next actions.",
  },
  {
    id: "r10",
    title: "Broker Communication Template",
    programId: "safechoice-program",
    topic: "Communications",
    resourceType: "Guide",
    dateLabel: "Mar 17, 2026",
    audience: "Operations / Distribution",
    description: "Reusable carrier-facing communication template for broker updates.",
  },
];

export const recentlyViewedResources: ResourceItem[] = [
  {
    id: "rv1",
    title: "Program Administrator Agreement",
    programId: "interboro-preferred",
    topic: "Agreements",
    resourceType: "Governing Doc",
    dateLabel: "Viewed 2 hours ago",
    audience: "Leadership / Legal",
    description: "Core governing agreement defining the program relationship.",
  },
  {
    id: "rv2",
    title: "January Operating Review Summary",
    programId: "safechoice-program",
    topic: "Operating Reviews",
    resourceType: "Meeting Summary",
    dateLabel: "Viewed yesterday",
    audience: "Leadership / Operations",
    description: "Summary of January review outcomes, decisions, and follow-up actions.",
  },
  {
    id: "rv3",
    title: "Quarterly Reporting Field Guide",
    programId: "interboro-specialty",
    topic: "Reporting",
    resourceType: "Guide",
    dateLabel: "Viewed 3 days ago",
    audience: "Finance / Operations",
    description: "Reference guide for recurring quarterly reporting structure and timing.",
  },
];

export const workItems: WorkItem[] = [
  {
    id: "w1",
    title: "Modeling request for Q2 scenarios",
    programId: "interboro-specialty",
    topic: "Modeling & Projections",
    stage: "In Progress",
    priority: "High",
    targetDate: "Apr 8, 2026",
    submittedBy: "Carrier Analyst",
    detail: "Requested updated scenario modeling to support the next operating review.",
  },
  {
    id: "w2",
    title: "Underwriting guideline clarification",
    programId: "safechoice-program",
    topic: "Product & Underwriting",
    stage: "Complete - Pending Review",
    priority: "Medium",
    targetDate: "Mar 21, 2026",
    submittedBy: "Carrier Ops",
    detail: "Clarification package is ready for carrier-side review.",
  },
  {
    id: "w3",
    title: "Operating Review action: confirm retention assumptions",
    programId: "interboro-preferred",
    topic: "Operating Reviews",
    stage: "Submitted",
    priority: "High",
    targetDate: "Mar 27, 2026",
    submittedBy: "Carrier Ops Lead",
    detail: "Action captured in the monthly review and now queued for follow-up.",
  },
  {
    id: "w4",
    title: "Data field mapping confirmation",
    programId: "interboro-preferred",
    topic: "Reporting",
    stage: "Confirmed Receipt",
    priority: "Low",
    targetDate: "Mar 25, 2026",
    submittedBy: "Finance",
    detail: "Waiting for SageSure team to validate the final reporting field mapping.",
  },
  {
    id: "w5",
    title: "Claims process document request",
    programId: "interboro-specialty",
    topic: "Claims",
    stage: "Complete",
    priority: "Medium",
    targetDate: "Mar 15, 2026",
    submittedBy: "Program Manager",
    detail: "Requested claims servicing resource was delivered and closed.",
  },
  {
    id: "w6",
    title: "Audit support package request",
    programId: "interboro-specialty",
    topic: "Audit/Compliance",
    stage: "In Progress",
    priority: "High",
    targetDate: "Apr 2, 2026",
    submittedBy: "Compliance Lead",
    detail: "Request for supporting documentation and exports for the next audit window.",
  },
  {
    id: "w7",
    title: "Commission settlement reconciliation question",
    programId: "interboro-preferred",
    topic: "Contracting",
    stage: "Submitted",
    priority: "Medium",
    targetDate: "Mar 28, 2026",
    submittedBy: "Finance",
    detail: "Carrier finance team submitted a reconciliation question related to settlement timing.",
  },
  {
    id: "w8",
    title: "Resource library access clarification",
    programId: "safechoice-program",
    topic: "Communications",
    stage: "Confirmed Receipt",
    priority: "Low",
    targetDate: "Mar 24, 2026",
    submittedBy: "Carrier Ops",
    detail: "Question submitted regarding visibility and access rules for shared resources.",
  },
  {
    id: "w9",
    title: "Presentation support request for board meeting",
    programId: "safechoice-program",
    topic: "Presentation Support",
    stage: "In Progress",
    priority: "Medium",
    targetDate: "Apr 5, 2026",
    submittedBy: "Program Manager",
    detail: "Support requested for a board presentation summarizing recent program movement.",
  },
  {
    id: "w10",
    title: "Portfolio monitoring threshold follow-up",
    programId: "interboro-preferred",
    topic: "Portfolio",
    stage: "Complete - Pending Review",
    priority: "High",
    targetDate: "Mar 23, 2026",
    submittedBy: "Carrier Ops Lead",
    detail: "Follow-up request related to new threshold alerts and monitoring assumptions.",
  },
];

export const metricSearchResults = [
  {
    id: "metric-1",
    type: "Metric" as const,
    title: "Retention trend by month",
    description: "Embedded KPI module with path to full BI analysis.",
    programId: "safechoice-program",
    programName: "SafeChoice Program",
    topic: "Reporting & Analysis",
    dateLabel: "Updated today",
    actionLabel: "Open BI Analysis",
  },
  {
    id: "metric-2",
    type: "Metric" as const,
    title: "Loss ratio trend by quarter",
    description: "Quarterly loss ratio view tied to the program performance dashboard.",
    programId: "interboro-specialty",
    programName: "Interboro Specialty",
    topic: "Reporting & Analysis",
    dateLabel: "Updated this week",
    actionLabel: "Open BI Analysis",
  },
];

export const defaultAgendaItems: ReviewAgendaItem[] = [
  {
    id: "g1",
    title: "Production trends review",
    description: "Review production movement and current portfolio trajectory.",
    durationMinutes: 15,
    presenter: "Partner UW Lead",
    slideReference: "Slides 1-4",
  },
  {
    id: "g2",
    title: "Loss performance analysis",
    description: "Walk through loss movement and notable patterns.",
    durationMinutes: 20,
    presenter: "MGA Claims Lead",
    slideReference: "Slides 5-9",
  },
  {
    id: "g3",
    title: "Profitability review",
    description: "Review profitability against plan and identify watch-outs.",
    durationMinutes: 15,
    presenter: "Portfolio Manager",
    slideReference: "Slides 10-20",
  },
  {
    id: "g4",
    title: "UW guidelines updates",
    description: "Discuss any material underwriting changes.",
    durationMinutes: 10,
    presenter: "MGA Underwriting",
    slideReference: "Slides 21-22",
  },
];

const participantPool: ReviewParticipant[] = [
  { id: "p1", name: "KJ", email: "kj1@example.com" },
  { id: "p2", name: "KJ", email: "kj2@example.com" },
  { id: "p3", name: "KJ", email: "kj3@example.com" },
  { id: "p4", name: "KJ", email: "kj4@example.com" },
  { id: "p5", name: "KJ", email: "kj5@example.com" },
  { id: "p6", name: "KJ", email: "kj6@example.com" },
  { id: "p7", name: "KJ", email: "kj7@example.com" },
  { id: "p8", name: "KJ", email: "kj8@example.com" },
  { id: "p9", name: "KJ", email: "kj9@example.com" },
];

export const operatingReviews: OperatingReview[] = [
  {
    id: "or-1",
    holdingCo: "Valence",
    title: "March 2026 operating review",
    meetingDate: "2026-03-15",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timezoneLabel: "EST",
    programIds: ["interboro-preferred", "interboro-specialty"],
    participants: participantPool.slice(0, 8),
    agendaItems: [
      { id: "or1-a1", title: "Production trends review", description: "Review production trends.", durationMinutes: 15, presenter: "Partner UW Lead", slideReference: "Slides 1-4" },
      { id: "or1-a2", title: "Loss performance analysis", description: "Discuss loss performance trends.", durationMinutes: 20, presenter: "MGA Claims Lead", slideReference: "Slides 5-9" },
      { id: "or1-a3", title: "Profitability review", description: "Review profitability against plan.", durationMinutes: 15, presenter: "Portfolio Manager", slideReference: "Slides 10-20" },
      { id: "or1-a4", title: "UW guidelines updates", description: "Review underwriting guideline changes.", durationMinutes: 10, presenter: "MGA Underwriting", slideReference: "Slides 21-22" },
    ],
    summary: [
      "Agreed to adjust rate plan for segment B and effective March 1",
      "Loss trends showing improvement in auto liability line",
      "Discussed expanding into two new states - action items created",
      "Q1 production goal set at $8.5M premium",
    ],
    preReadResourceIds: ["r1", "r8", "r2"],
    status: "Upcoming",
    keyTopics: ["Production trends", "Loss performance", "Profitability review"],
  },
  {
    id: "or-2",
    holdingCo: "Valence",
    title: "February 2026 operating review",
    meetingDate: "2026-02-14",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timezoneLabel: "EST",
    programIds: ["interboro-preferred", "interboro-specialty"],
    participants: participantPool.slice(0, 8),
    agendaItems: [
      { id: "or2-a1", title: "Production trends review", description: "Review production trends.", durationMinutes: 15, presenter: "Partner UW Lead", slideReference: "Slides 1-4" },
      { id: "or2-a2", title: "Loss performance analysis", description: "Discuss loss performance trends.", durationMinutes: 20, presenter: "MGA Claims Lead", slideReference: "Slides 5-9" },
      { id: "or2-a3", title: "Profitability review", description: "Review profitability against plan.", durationMinutes: 15, presenter: "Portfolio Manager", slideReference: "Slides 10-20" },
      { id: "or2-a4", title: "UW guidelines updates", description: "Review underwriting guideline changes.", durationMinutes: 10, presenter: "MGA Underwriting", slideReference: "Slides 21-22" },
    ],
    summary: [
      "Reviewed February portfolio trends across Interboro programs",
      "Confirmed loss performance improvement in one segment",
      "Discussed profitability trajectory and updated action tracking",
    ],
    preReadResourceIds: ["r2", "r9", "r6"],
    status: "Completed",
    keyTopics: ["Production trends", "Loss performance", "Profitability review"],
  },
  {
    id: "or-3",
    holdingCo: "Valence",
    title: "January 2026 operating review",
    meetingDate: "2026-01-18",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timezoneLabel: "EST",
    programIds: ["interboro-preferred", "interboro-specialty"],
    participants: participantPool.slice(0, 9),
    agendaItems: [
      { id: "or3-a1", title: "Animal planning", description: "Kickoff planning topics.", durationMinutes: 15, presenter: "Partner UW Lead", slideReference: "Slides 1-4" },
      { id: "or3-a2", title: "Rate strategy", description: "Discuss rate strategy.", durationMinutes: 15, presenter: "Portfolio Manager", slideReference: "Slides 5-10" },
      { id: "or3-a3", title: "Market outlook", description: "Discuss market outlook.", durationMinutes: 15, presenter: "All", slideReference: "Slides 11-18" },
      { id: "or3-a4", title: "Action alignment", description: "Finalize actions and next steps.", durationMinutes: 15, presenter: "Program Manager", slideReference: "Slides 19-22" },
    ],
    summary: [
      "Reviewed early-year strategy priorities and market outlook",
      "Identified rate strategy follow-ups and resource needs",
    ],
    preReadResourceIds: ["r6", "r7"],
    status: "Completed",
    keyTopics: ["Animal planning", "Rate strategy", "Market outlook"],
  },
  {
    id: "or-4",
    holdingCo: "Valence",
    title: "December 2025 operating review",
    meetingDate: "2025-12-13",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timezoneLabel: "EST",
    programIds: ["interboro-preferred"],
    participants: participantPool.slice(0, 7),
    agendaItems: [
      { id: "or4-a1", title: "Year-end review", description: "Review year-end performance.", durationMinutes: 20, presenter: "Portfolio Manager", slideReference: "Slides 1-6" },
      { id: "or4-a2", title: "2026 strategy", description: "Discuss 2026 strategy.", durationMinutes: 20, presenter: "Partner UW Lead", slideReference: "Slides 7-12" },
      { id: "or4-a3", title: "Renewal performance", description: "Review renewal performance.", durationMinutes: 20, presenter: "MGA Underwriting", slideReference: "Slides 13-18" },
    ],
    summary: ["Reviewed year-end outcomes and set 2026 priorities."],
    preReadResourceIds: ["r1", "r7"],
    status: "Completed",
    keyTopics: ["Year-end review", "2026 strategy", "Renewal performance"],
  },
  {
    id: "or-5",
    holdingCo: "Valence",
    title: "April 2026 operating review",
    meetingDate: "2026-04-19",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timezoneLabel: "EST",
    programIds: ["interboro-preferred", "interboro-specialty", "safechoice-program"],
    participants: participantPool.slice(0, 9),
    agendaItems: [
      { id: "or5-a1", title: "Retention review", description: "Retention review", durationMinutes: 15, presenter: "Partner UW Lead", slideReference: "Slides 1-4" },
      { id: "or5-a2", title: "Product launch", description: "Product launch", durationMinutes: 15, presenter: "MGA Underwriting", slideReference: "Slides 5-8" },
      { id: "or5-a3", title: "UW guidelines", description: "UW guidelines", durationMinutes: 15, presenter: "Portfolio Manager", slideReference: "Slides 9-12" },
      { id: "or5-a4", title: "Action alignment", description: "Action alignment", durationMinutes: 15, presenter: "Program Manager", slideReference: "Slides 13-16" },
    ],
    summary: [],
    preReadResourceIds: ["r8", "r3", "r10"],
    status: "Upcoming",
    keyTopics: ["Retention review", "Product launch", "UW guidelines"],
  },
  {
    id: "or-6",
    holdingCo: "Valence",
    title: "May 2026 operating review",
    meetingDate: "2026-05-17",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    timezoneLabel: "EST",
    programIds: ["safechoice-program"],
    participants: participantPool.slice(0, 6),
    agendaItems: [
      { id: "or6-a1", title: "Performance recap", description: "Performance recap", durationMinutes: 20, presenter: "Portfolio Manager", slideReference: "Slides 1-4" },
      { id: "or6-a2", title: "Communications review", description: "Communications review", durationMinutes: 20, presenter: "Program Manager", slideReference: "Slides 5-8" },
      { id: "or6-a3", title: "Action alignment", description: "Action alignment", durationMinutes: 20, presenter: "All", slideReference: "Slides 9-12" },
    ],
    summary: [],
    preReadResourceIds: ["r10", "r8"],
    status: "Upcoming",
    keyTopics: ["Performance recap", "Communications review", "Action alignment"],
  },
];

export const actionsAndAgreements: ActionAgreement[] = [
  {
    id: "aa-1",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-preferred", "interboro-specialty"],
    title: "2026 Financial budget",
    description:
      "SageSure to redistribute an updated SURE and Elevate 2026 financial budget with following additions: inclusion of a 'cat contingency' acting as a net cat loss cushion, inclusion of a non-cat loss cushion, and inclusion of reinsurance cost allocation details",
    status: "Confirmed Receipt",
    isArchived: false,
    attachments: [{ id: "f1", name: "repair_estimate-A.doc", sizeLabel: "1 MB" }],
  },
  {
    id: "aa-2",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-specialty"],
    title: "Claims readiness follow-up",
    description: "SageSure actuarial to follow up to Underwriting Oversight Committee on updated claims readiness assumptions.",
    status: "Complete",
    isArchived: true,
    attachments: [],
  },
  {
    id: "aa-3",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-specialty"],
    title: "Commercial launch planning",
    description: "SageSure Commercial to move forward with plans to launch a Commercial BOP property only product in all states.",
    status: "Complete",
    isArchived: true,
    attachments: [{ id: "f2", name: "launch_plan.pdf", sizeLabel: "2 MB" }],
  },
  {
    id: "aa-4",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-specialty"],
    title: "Per-risk reinsurance communication",
    description: "SageSure to communicate details on the new per risk reinsurance structure to impacted stakeholders.",
    status: "Complete",
    isArchived: true,
    attachments: [],
  },
  {
    id: "aa-5",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-preferred", "interboro-specialty"],
    title: "Interboro review cadence",
    description: "SageSure to conduct reviews of all Interboro Preferred and Specialty programs in a consolidated cadence.",
    status: "Complete",
    isArchived: true,
    attachments: [],
  },
  {
    id: "aa-6",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-specialty"],
    title: "Underwriting committee follow-up",
    description: "SageSure actuarial to follow up to Underwriting Oversight Committee with revised assumptions.",
    status: "Complete",
    isArchived: true,
    attachments: [],
  },
  {
    id: "aa-7",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-specialty"],
    title: "Reinsurance communication",
    description: "SageSure to communicate details on the new per risk reinsurance arrangement.",
    status: "Complete",
    isArchived: true,
    attachments: [],
  },
  {
    id: "aa-8",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-specialty"],
    title: "Committee pack follow-up",
    description: "SageSure actuarial to follow up with revised committee pack and supporting assumptions.",
    status: "Complete",
    isArchived: true,
    attachments: [],
  },
  {
    id: "aa-9",
    holdingCo: "Valence",
    reviewId: "or-2",
    meetingDate: "2026-02-14",
    deliveredDate: "2026-02-20",
    programIds: ["interboro-preferred", "interboro-specialty"],
    title: "Interboro consolidated review plan",
    description: "SageSure to conduct reviews of all Interboro Preferred and related programs on a consistent cadence.",
    status: "Complete",
    isArchived: true,
    attachments: [],
  },
  {
    id: "aa-10",
    holdingCo: "Valence",
    reviewId: "or-1",
    meetingDate: "2026-03-15",
    deliveredDate: "2026-03-20",
    programIds: ["interboro-preferred", "interboro-specialty"],
    title: "Threshold monitoring follow-up",
    description: "Follow-up on new threshold alerts and monitoring assumptions discussed during the March operating review.",
    status: "Complete - Pending Review",
    isArchived: false,
    attachments: [],
  },
  {
    id: "aa-11",
    holdingCo: "Valence",
    reviewId: "or-1",
    meetingDate: "2026-03-15",
    deliveredDate: "2026-03-20",
    programIds: ["interboro-preferred"],
    title: "Retention assumption clarification",
    description: "Clarify updated retention assumptions and owner responsibilities before next review.",
    status: "In Progress",
    isArchived: false,
    attachments: [],
  },
  {
    id: "aa-12",
    holdingCo: "Valence",
    reviewId: "or-1",
    meetingDate: "2026-03-15",
    deliveredDate: "2026-03-20",
    programIds: ["interboro-specialty"],
    title: "Budget redistribution follow-up",
    description: "Redistribute the revised 2026 budget pack with updated assumptions and notes.",
    status: "Submitted",
    isArchived: false,
    attachments: [],
  },
];