import type {
  ActivityItem,
  Program,
  RelationshipStat,
  ResourceItem,
  ReviewAgendaItem,
  WorkItem,
} from "@/lib/types/portal";

export const relationshipStats: RelationshipStat[] = [
  {
    label: "Active Programs",
    value: "3",
    subtext: "Across your SageSure relationship",
  },
  {
    label: "Needs Attention",
    value: "6",
    subtext: "Items awaiting carrier input",
  },
  {
    label: "In Motion",
    value: "11",
    subtext: "Requests and actions progressing",
  },
  {
    label: "Delivered This Month",
    value: "24",
    subtext: "Reports, updates, and resources posted",
  },
];

export const programs: Program[] = [
  {
    id: "interboro-preferred",
    carrierGroup: "Valence Insurance Holdings",
    carrier: "Interboro",
    name: "Interboro Preferred",
    status: "Active",
    openWorkCount: 4,
    nextReviewDate: "Mar 29, 2026",
    latestUpdate: "January loss ratio package posted",
    metrics: {
      production: "↑ 4.2%",
      retention: "→ 88.1%",
      lossRatio: "↓ 2.1 pts",
    },
  },
  {
    id: "safechoice-program",
    carrierGroup: "SafeChoice Group",
    carrier: "SafeChoice",
    name: "SafeChoice Program",
    status: "Active",
    openWorkCount: 3,
    nextReviewDate: "Apr 03, 2026",
    latestUpdate: "New underwriting guideline update",
    metrics: {
      production: "→ 0.8%",
      retention: "↑ 1.4 pts",
      lossRatio: "→ 61.3%",
    },
  },
  {
    id: "interboro-specialty",
    carrierGroup: "Valence Insurance Holdings",
    carrier: "Interboro",
    name: "Interboro Specialty",
    status: "Watch",
    openWorkCount: 7,
    nextReviewDate: "Apr 07, 2026",
    latestUpdate: "Modeling request currently in progress",
    metrics: {
      production: "↓ 1.3%",
      retention: "→ 84.7%",
      lossRatio: "↑ 3.8 pts",
    },
  },
];

export const activityItems: ActivityItem[] = [
  {
    id: "a1",
    programId: "interboro-preferred",
    type: "scheduled_report_available",
    title: "Monthly financial report available",
    detail: "Interboro Preferred March report was posted to the Resource Library.",
    timestamp: "Today • 9:12 AM",
    timeBucket: "Today",
    priority: "High",
    relatedEntityType: "resource",
    relatedEntityId: "r1",
  },
  {
    id: "a2",
    programId: "safechoice-program",
    type: "request_stage_changed",
    title: "Request moved to Complete - Pending Review",
    detail: "Underwriting guideline clarification is ready for review.",
    timestamp: "Today • 8:40 AM",
    timeBucket: "Today",
    priority: "Normal",
    relatedEntityType: "work",
    relatedEntityId: "w2",
  },
  {
    id: "a3",
    programId: "interboro-specialty",
    type: "review_scheduled",
    title: "Operating Review scheduled",
    detail: "Review scheduled for Apr 07, 2026 with pre-read materials attached.",
    timestamp: "Yesterday • 4:20 PM",
    timeBucket: "This Week",
    priority: "Normal",
    relatedEntityType: "review",
    relatedEntityId: "review-draft-1",
  },
  {
    id: "a4",
    programId: "interboro-specialty",
    type: "resource_published",
    title: "Cat response bulletin posted",
    detail: "New catastrophe prep resource is now visible to program users.",
    timestamp: "Yesterday • 2:05 PM",
    timeBucket: "This Week",
    priority: "Normal",
    relatedEntityType: "resource",
    relatedEntityId: "r5",
  },
  {
    id: "a5",
    programId: "interboro-preferred",
    type: "summary_posted",
    title: "Operating Review summary posted",
    detail: "A new summary and related action items are now available.",
    timestamp: "Mar 18 • 11:10 AM",
    timeBucket: "Earlier",
    priority: "Normal",
    relatedEntityType: "resource",
    relatedEntityId: "rv1",
  },
  {
    id: "a6",
    programId: "interboro-specialty",
    type: "request_created",
    title: "New modeling request submitted",
    detail: "Carrier analyst submitted a modeling request for Q2 scenarios.",
    timestamp: "Mar 16 • 3:25 PM",
    timeBucket: "Earlier",
    priority: "High",
    relatedEntityType: "work",
    relatedEntityId: "w1",
  },
  {
    id: "a7",
    programId: "interboro-preferred",
    type: "resource_published",
    title: "Program Administrator Agreement restatement posted",
    detail: "Updated governing agreement language is now available in the library.",
    timestamp: "Today • 7:55 AM",
    timeBucket: "Today",
    priority: "Normal",
    relatedEntityType: "resource",
    relatedEntityId: "r6",
  },
  {
    id: "a8",
    programId: "safechoice-program",
    type: "scheduled_report_available",
    title: "Retention monitoring package delivered",
    detail: "A new retention monitoring report has been posted for SafeChoice.",
    timestamp: "Yesterday • 1:20 PM",
    timeBucket: "This Week",
    priority: "Normal",
    relatedEntityType: "resource",
    relatedEntityId: "r8",
  },
  {
    id: "a9",
    programId: "interboro-preferred",
    type: "request_stage_changed",
    title: "Reporting field mapping moved to Confirmed Receipt",
    detail: "Carrier Ops acknowledged the updated reporting field mapping request.",
    timestamp: "Yesterday • 9:10 AM",
    timeBucket: "This Week",
    priority: "Low",
    relatedEntityType: "work",
    relatedEntityId: "w4",
  },
  {
    id: "a10",
    programId: "safechoice-program",
    type: "resource_published",
    title: "Broker communication template added",
    detail: "New communication template has been added for distribution support.",
    timestamp: "Mar 17 • 2:14 PM",
    timeBucket: "Earlier",
    priority: "Normal",
    relatedEntityType: "resource",
    relatedEntityId: "r10",
  },
  {
    id: "a11",
    programId: "interboro-specialty",
    type: "summary_posted",
    title: "Claims readiness summary posted",
    detail: "A claims readiness summary has been posted following this week’s review.",
    timestamp: "Mar 15 • 5:04 PM",
    timeBucket: "Earlier",
    priority: "Normal",
    relatedEntityType: "resource",
    relatedEntityId: "r9",
  },
  {
    id: "a12",
    programId: "safechoice-program",
    type: "request_created",
    title: "New presentation support request submitted",
    detail: "Carrier team submitted a presentation support request for next month’s board materials.",
    timestamp: "Mar 14 • 10:45 AM",
    timeBucket: "Earlier",
    priority: "Normal",
    relatedEntityType: "work",
    relatedEntityId: "w9",
  },
];

export const resources: ResourceItem[] = [
  {
    id: "r1",
    title: "March Financial Report",
    programId: "interboro-preferred",
    topic: "Financial Reporting",
    resourceType: "Report",
    dateLabel: "Mar 18, 2026",
    audience: "Leadership / Finance",
    description:
      "Monthly performance package with production, retention, and loss ratio views.",
  },
  {
    id: "r2",
    title: "February Operating Review Deck",
    programId: "interboro-preferred",
    topic: "Operating Reviews",
    resourceType: "Review Deck",
    dateLabel: "Mar 3, 2026",
    audience: "Leadership / Operations",
    description:
      "Plan vs Actual review, portfolio movement, and action items.",
  },
  {
    id: "r3",
    title: "Underwriting Guideline Update",
    programId: "safechoice-program",
    topic: "Product & Underwriting",
    resourceType: "Product Update",
    dateLabel: "Feb 18, 2026",
    audience: "Operations / Underwriting",
    description:
      "Latest underwriting changes affecting new business flow.",
  },
  {
    id: "r4",
    title: "Claims Services Addendum",
    programId: "interboro-specialty",
    topic: "Agreements",
    resourceType: "Governing Doc",
    dateLabel: "Feb 11, 2026",
    audience: "Legal / Leadership",
    description:
      "Updated agreement language related to program servicing responsibilities.",
  },
  {
    id: "r5",
    title: "Catastrophe Readiness Bulletin",
    programId: "interboro-specialty",
    topic: "Cat Response",
    resourceType: "Guide",
    dateLabel: "Yesterday",
    audience: "Operations",
    description:
      "Current operating guidance for catastrophe season readiness.",
  },
  {
    id: "r6",
    title: "Program Administrator Agreement Restatement",
    programId: "interboro-preferred",
    topic: "Agreements",
    resourceType: "Governing Doc",
    dateLabel: "Today",
    audience: "Leadership / Legal",
    description:
      "Restated administrator agreement consolidating prior amendments.",
  },
  {
    id: "r7",
    title: "Commission Settlement Template",
    programId: "interboro-preferred",
    topic: "Contracting",
    resourceType: "Guide",
    dateLabel: "Mar 12, 2026",
    audience: "Finance / Leadership",
    description:
      "Template and guidance for commission settlement reconciliation.",
  },
  {
    id: "r8",
    title: "Retention Monitoring Package",
    programId: "safechoice-program",
    topic: "Reporting & Analysis",
    resourceType: "Report",
    dateLabel: "Mar 19, 2026",
    audience: "Leadership / Operations",
    description:
      "A new package focused on retention trends, segments, and watch-outs.",
  },
  {
    id: "r9",
    title: "Claims Readiness Summary",
    programId: "interboro-specialty",
    topic: "Claims",
    resourceType: "Meeting Summary",
    dateLabel: "Mar 15, 2026",
    audience: "Operations / Claims",
    description:
      "Post-review summary outlining claims readiness, bottlenecks, and next actions.",
  },
  {
    id: "r10",
    title: "Broker Communication Template",
    programId: "safechoice-program",
    topic: "Communications",
    resourceType: "Guide",
    dateLabel: "Mar 17, 2026",
    audience: "Operations / Distribution",
    description:
      "Reusable carrier-facing communication template for broker updates.",
  },
];

export const recentlyViewedResources: ResourceItem[] = [
  {
    id: "rv1",
    title: "Program Administrator Agreement",
    programId: "interboro-preferred",
    topic: "Agreements",
    resourceType: "Governing Doc",
    dateLabel: "Viewed 2 hours ago",
    audience: "Leadership / Legal",
    description:
      "Core governing agreement defining the program relationship.",
  },
  {
    id: "rv2",
    title: "January Operating Review Summary",
    programId: "safechoice-program",
    topic: "Operating Reviews",
    resourceType: "Meeting Summary",
    dateLabel: "Viewed yesterday",
    audience: "Leadership / Operations",
    description:
      "Summary of January review outcomes, decisions, and follow-up actions.",
  },
  {
    id: "rv3",
    title: "Quarterly Reporting Field Guide",
    programId: "interboro-specialty",
    topic: "Reporting",
    resourceType: "Guide",
    dateLabel: "Viewed 3 days ago",
    audience: "Finance / Operations",
    description:
      "Reference guide for recurring quarterly reporting structure and timing.",
  },
  {
    id: "rv4",
    title: "Board Presentation Outline",
    programId: "safechoice-program",
    topic: "Presentation Support",
    resourceType: "Guide",
    dateLabel: "Viewed today",
    audience: "Leadership",
    description:
      "Outline and guidance for preparing program-level board presentations.",
  },
  {
    id: "rv5",
    title: "Audit Documentation Checklist",
    programId: "interboro-specialty",
    topic: "Audit/Compliance",
    resourceType: "Guide",
    dateLabel: "Viewed 2 days ago",
    audience: "Compliance / Operations",
    description:
      "Checklist of required support documents for audit and compliance review.",
  },
  {
    id: "rv6",
    title: "Prior Month Financial Variance Commentary",
    programId: "interboro-preferred",
    topic: "Reporting & Analysis",
    resourceType: "Meeting Summary",
    dateLabel: "Viewed last week",
    audience: "Finance / Leadership",
    description:
      "Narrative commentary explaining prior month performance variance.",
  },
];

export const workItems: WorkItem[] = [
  {
    id: "w1",
    title: "Modeling request for Q2 scenarios",
    programId: "interboro-specialty",
    topic: "Modeling & Projections",
    stage: "In Progress",
    priority: "High",
    targetDate: "Apr 8, 2026",
    submittedBy: "Carrier Analyst",
    detail:
      "Requested updated scenario modeling to support the next operating review.",
  },
  {
    id: "w2",
    title: "Underwriting guideline clarification",
    programId: "safechoice-program",
    topic: "Product & Underwriting",
    stage: "Complete - Pending Review",
    priority: "Medium",
    targetDate: "Mar 21, 2026",
    submittedBy: "Carrier Ops",
    detail: "Clarification package is ready for carrier-side review.",
  },
  {
    id: "w3",
    title: "Operating Review action: confirm retention assumptions",
    programId: "interboro-preferred",
    topic: "Operating Reviews",
    stage: "Submitted",
    priority: "High",
    targetDate: "Mar 27, 2026",
    submittedBy: "Carrier Ops Lead",
    detail:
      "Action captured in the monthly review and now queued for follow-up.",
  },
  {
    id: "w4",
    title: "Data field mapping confirmation",
    programId: "interboro-preferred",
    topic: "Reporting",
    stage: "Confirmed Receipt",
    priority: "Low",
    targetDate: "Mar 25, 2026",
    submittedBy: "Finance",
    detail:
      "Waiting for SageSure team to validate the final reporting field mapping.",
  },
  {
    id: "w5",
    title: "Claims process document request",
    programId: "interboro-specialty",
    topic: "Claims",
    stage: "Complete",
    priority: "Medium",
    targetDate: "Mar 15, 2026",
    submittedBy: "Program Manager",
    detail: "Requested claims servicing resource was delivered and closed.",
  },
  {
    id: "w6",
    title: "Audit support package request",
    programId: "interboro-specialty",
    topic: "Audit/Compliance",
    stage: "In Progress",
    priority: "High",
    targetDate: "Apr 2, 2026",
    submittedBy: "Compliance Lead",
    detail:
      "Request for supporting documentation and exports for the next audit window.",
  },
  {
    id: "w7",
    title: "Commission settlement reconciliation question",
    programId: "interboro-preferred",
    topic: "Contracting",
    stage: "Submitted",
    priority: "Medium",
    targetDate: "Mar 28, 2026",
    submittedBy: "Finance",
    detail:
      "Carrier finance team submitted a reconciliation question related to settlement timing.",
  },
  {
    id: "w8",
    title: "Resource library access clarification",
    programId: "safechoice-program",
    topic: "Communications",
    stage: "Confirmed Receipt",
    priority: "Low",
    targetDate: "Mar 24, 2026",
    submittedBy: "Carrier Ops",
    detail:
      "Question submitted regarding visibility and access rules for shared resources.",
  },
  {
    id: "w9",
    title: "Presentation support request for board meeting",
    programId: "safechoice-program",
    topic: "Presentation Support",
    stage: "In Progress",
    priority: "Medium",
    targetDate: "Apr 5, 2026",
    submittedBy: "Program Manager",
    detail:
      "Support requested for a board presentation summarizing recent program movement.",
  },
  {
    id: "w10",
    title: "Portfolio monitoring threshold follow-up",
    programId: "interboro-preferred",
    topic: "Portfolio",
    stage: "Complete - Pending Review",
    priority: "High",
    targetDate: "Mar 23, 2026",
    submittedBy: "Carrier Ops Lead",
    detail:
      "Follow-up request related to new threshold alerts and monitoring assumptions.",
  },
];

export const metricSearchResults = [
  {
    id: "metric-1",
    type: "Metric" as const,
    title: "Retention trend by month",
    description: "Embedded KPI module with path to full BI analysis.",
    programId: "safechoice-program",
    programName: "SafeChoice Program",
    topic: "Reporting & Analysis",
    dateLabel: "Updated today",
    actionLabel: "Open BI Analysis",
  },
  {
    id: "metric-2",
    type: "Metric" as const,
    title: "Loss ratio trend by quarter",
    description:
      "Quarterly loss ratio view tied to the program performance dashboard.",
    programId: "interboro-specialty",
    programName: "Interboro Specialty",
    topic: "Reporting & Analysis",
    dateLabel: "Updated this week",
    actionLabel: "Open BI Analysis",
  },
];

export const defaultAgendaItems: ReviewAgendaItem[] = [
  {
    id: "g1",
    title: "Portfolio performance overview",
    description: "Review production, retention, and loss ratio movement.",
    durationMinutes: 15,
    presenter: "Carrier Ops Lead",
    slideReference: "Slides 3-8",
  },
  {
    id: "g2",
    title: "Rate and underwriting updates",
    description: "Walk through meaningful policy and guideline changes.",
    durationMinutes: 10,
    presenter: "Underwriting",
    slideReference: "Slides 9-12",
  },
  {
    id: "g3",
    title: "Action items and decisions",
    description: "Capture commitments, owners, and follow-up timing.",
    durationMinutes: 10,
    presenter: "Program Manager",
    slideReference: "Slides 13-15",
  },
];